import type { ThemeDefinitions } from './theme-types';

/** Семантические цвета — общие для всех тем */
const SUCCESS = '#16a34a';
const DANGER = '#dc3545';
const DANGER_FOCUS = 'rgba(220, 53, 69, 0.25)';

export const themeDefinitions: ThemeDefinitions = {
	default: {
		light: {
			'--color-bg': '#f8fafc',
			'--color-surface': '#ffffff',
			'--color-text': '#1e293b',
			'--color-text-muted': '#64748b',
			'--color-border': '#cbd5e1',
			'--color-border-light': '#e2e8f0',
			'--color-primary': '#3b82f6',
			'--color-primary-hover': '#2563eb',
			'--color-on-primary': '#ffffff',
			'--color-bg-hover': '#e2e8f0',
			'--gradient-bg': 'linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(59, 130, 246, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
		dark: {
			'--color-bg': '#1e293b',
			'--color-surface': '#0f172a',
			'--color-text': '#f1f5f9',
			'--color-text-muted': '#94a3b8',
			'--color-border': '#334155',
			'--color-border-light': '#475569',
			'--color-primary': '#3b82f6',
			'--color-primary-hover': '#2563eb',
			'--color-on-primary': '#ffffff',
			'--color-bg-hover': '#475569',
			'--gradient-bg': 'linear-gradient(180deg, #1e293b 0%, #17202e 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(59, 130, 246, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
	},
	ocean: {
		light: {
			'--color-bg': '#f0f9ff',
			'--color-surface': '#ffffff',
			'--color-text': '#0c4a6e',
			'--color-text-muted': '#0369a1',
			'--color-border': '#7dd3fc',
			'--color-border-light': '#bae6fd',
			'--color-primary': '#0ea5e9',
			'--color-primary-hover': '#0284c7',
			'--color-on-primary': '#ffffff',
			'--color-bg-hover': '#bae6fd',
			'--gradient-bg': 'linear-gradient(180deg, #f0f9ff 0%, #e0f2fe 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(14, 165, 233, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
		dark: {
			'--color-bg': '#0c4a6e',
			'--color-surface': '#075985',
			'--color-text': '#f0f9ff',
			'--color-text-muted': '#7dd3fc',
			'--color-border': '#0e7490',
			'--color-border-light': '#155e75',
			'--color-primary': '#38bdf8',
			'--color-primary-hover': '#0ea5e9',
			'--color-on-primary': '#0c4a6e',
			'--color-bg-hover': '#0e7490',
			'--gradient-bg': 'linear-gradient(180deg, #0c4a6e 0%, #075985 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(56, 189, 248, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
	},
	forest: {
		light: {
			'--color-bg': '#f0fdf4',
			'--color-surface': '#ffffff',
			'--color-text': '#052e16',
			'--color-text-muted': '#15803d',
			'--color-border': '#86efac',
			'--color-border-light': '#bbf7d0',
			'--color-primary': '#22c55e',
			'--color-primary-hover': '#16a34a',
			'--color-on-primary': '#ffffff',
			'--color-bg-hover': '#bbf7d0',
			'--gradient-bg': 'linear-gradient(180deg, #f0fdf4 0%, #dcfce7 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(34, 197, 94, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
		dark: {
			'--color-bg': '#052e16',
			'--color-surface': '#14532d',
			'--color-text': '#f0fdf4',
			'--color-text-muted': '#86efac',
			'--color-border': '#166534',
			'--color-border-light': '#15803d',
			'--color-primary': '#4ade80',
			'--color-primary-hover': '#22c55e',
			'--color-on-primary': '#052e16',
			'--color-bg-hover': '#15803d',
			'--gradient-bg': 'linear-gradient(180deg, #052e16 0%, #14532d 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(74, 222, 128, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
	},
	sunset: {
		light: {
			'--color-bg': '#fffbeb',
			'--color-surface': '#ffffff',
			'--color-text': '#451a03',
			'--color-text-muted': '#b45309',
			'--color-border': '#fcd34d',
			'--color-border-light': '#fde68a',
			'--color-primary': '#f59e0b',
			'--color-primary-hover': '#d97706',
			'--color-on-primary': '#ffffff',
			'--color-bg-hover': '#fde68a',
			'--gradient-bg': 'linear-gradient(180deg, #fffbeb 0%, #fef3c7 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(245, 158, 11, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
		dark: {
			'--color-bg': '#451a03',
			'--color-surface': '#78350f',
			'--color-text': '#fffbeb',
			'--color-text-muted': '#fcd34d',
			'--color-border': '#92400e',
			'--color-border-light': '#b45309',
			'--color-primary': '#fbbf24',
			'--color-primary-hover': '#f59e0b',
			'--color-on-primary': '#451a03',
			'--color-bg-hover': '#b45309',
			'--gradient-bg': 'linear-gradient(180deg, #451a03 0%, #78350f 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(251, 191, 36, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
	},
	lavender: {
		light: {
			'--color-bg': '#f5f3ff',
			'--color-surface': '#ffffff',
			'--color-text': '#3b0764',
			'--color-text-muted': '#6d28d9',
			'--color-border': '#c4b5fd',
			'--color-border-light': '#ddd6fe',
			'--color-primary': '#8b5cf6',
			'--color-primary-hover': '#7c3aed',
			'--color-on-primary': '#ffffff',
			'--color-bg-hover': '#ddd6fe',
			'--gradient-bg': 'linear-gradient(180deg, #f5f3ff 0%, #ede9fe 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(139, 92, 246, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
		dark: {
			'--color-bg': '#3b0764',
			'--color-surface': '#581c87',
			'--color-text': '#f5f3ff',
			'--color-text-muted': '#c4b5fd',
			'--color-border': '#7c3aed',
			'--color-border-light': '#6d28d9',
			'--color-primary': '#a78bfa',
			'--color-primary-hover': '#8b5cf6',
			'--color-on-primary': '#3b0764',
			'--color-bg-hover': '#6d28d9',
			'--gradient-bg': 'linear-gradient(180deg, #3b0764 0%, #581c87 100%)',
			'--color-success': SUCCESS,
			'--color-danger': DANGER,
			'--color-focus-ring': 'rgba(167, 139, 250, 0.25)',
			'--color-danger-focus': DANGER_FOCUS,
		},
	},
};
